---

dist: xenial
lanaguage: minimal
addons:
  apt:
    packages:
      - gdal-bin
script:
  - ./trigger.sh
env:
  - MAP=europe/germany
  - MAP=europe/germany/berlin
  - MAP=europe/austria
  - MAP=europe/switzerland
